# Generated by Django 3.1.2 on 2020-10-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201026_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='pintrest',
            new_name='pinterest',
        ),
    ]
