# Generated by Django 3.1.2 on 2020-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201026_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='role',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='about',
            name='roles',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
