# Generated by Django 3.1.2 on 2020-10-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201026_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='roles',
            field=models.CharField(max_length=200),
        ),
    ]
