# Generated by Django 3.1.2 on 2020-10-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
